// export const allColors = {
//     light: {
//         accentText: '#3489E4',
//         accentColorLight: '#C9D3EA',
//         inputBackground: '#DEDEDE',
//         iconColor: '#000000',
//         background: '#eee',
//         border: '#707070',
//         borderCurrency: '#FFF',
//         regularText: '#000000',
//         subText: '#7C7C7C',
//         buttonNumber: '#E68C01',
//         activeColor: '#8CF890',
//         unActiveColor: '#FF6D87',
//         positiveRate: '#8CF890',
//         negativeRate: '#FF6D87',
//     },
//     dark: {
//         accentText: '#16BFBF',
//         accentColorLight: '#384F6A',
//         inputBackground: '#636363',
//         iconColor: '#FFF',
//         background: '#3E3E41',
//         border: '#707070',
//         borderCurrency: '#FFF',
//         regularText: '#FFFFFF',
//         subText: '#CCCCCC',
//         buttonNumber: '#E68C01',
//         activeColor: '#8CF890',
//         unActiveColor: '#FF6D87',
//         positiveRate: '#8CF890',
//         negativeRate: '#FF6D87',
//     },
// };
export const allColors = {
    light: {
        buttonNumber: '#E68C01',
        positiveRate: '#8CF890',
        negativeRate: '#FF6D87',
        inputBackground: '#DEDEDE',
        accentText: '#3489E4',
        buttonText: '#FFFFFF',
        regularText: '#4E4E4E',
        titleText: '#000000',
        textAccentButton: '#155249',
        modalBackground: '#00000080',
        icon: '#000000',
        error: '#FF5010',
        low: '#2ECC71',
        medium: '#F7DC6F',
        high: '#E74C3C',
        shadow: '#bababa',
        background: '#E4ECF9',
        card: '#FFFFFF',
        lightButton: '#EDEDED',
        inactiveText: '#979797',
        accentColorLight1: '#C4AFF0',
        accentColorDark1: '#3F2150',
        accentColorLight: '#C9D3EA',
        accentColorDark: '#6D5BE0',
    },
    dark: {
        buttonNumber: '#E68C01',
        positiveRate: '#8CF890',
        negativeRate: '#FF6D87',
        inputBackground: '#636363',
        accentText: '#4C6EBB',
        buttonText: '#FFFFFF',
        regularText: '#f0f0f5',
        titleText: '#e9e9f0',
        textAccentButton: '#155249',
        modalBackground: '#00000080',
        icon: '#e9e9f0',
        error: '#FF5010',
        low: '#2ECC71',
        medium: '#F7DC6F',
        high: '#E74C3C',
        shadow: '#484848',
        background: '#12121a',
        card: '#0C0C0C',
        inactiveText: '#e6e6fc',
        accentColorLight1: '#C4AFF0',
        accentColorDark1: '#3F2150',
        accentColorLight: '#384F6A',
        accentColorDark: '#C4AFF0',
    },
};
