export const allColors = {
    light: {
        accentText: '#3489E4',
        accentColorLight: '#C9D3EA',
        inputBackground: '#DEDEDE',
        iconColor: '#000000',
        background: '#eee',
        border: '#707070',
        borderCurrency: '#FFF',
        regularText: '#000000',
        subText: '#7C7C7C',
        buttonNumber: '#E68C01',
    },
    dark: {
        accentText: '#16BFBF',
        accentColorLight: '#384F6A',
        inputBackground: '#636363',
        iconColor: '#FFF',
        background: '#3E3E41',
        border: '#707070',
        borderCurrency: '#FFF',
        regularText: '#FFFFFF',
        subText: '#CCCCCC',
        buttonNumber: '#E68C01',
    },
};
