export const countries = {
  AD: {
    countryName: 'Andorra',
    currency: 'EUR',
    symbol: '€',
    phcode: '376',
    code: 'AD',
  },
  AE: {
    countryName: 'United Arab EmIRateListItems',
    currency: 'AED',
    symbol: 'AED',
    dateFormat: 'dd/MM/yyyy',
    phcode: '971',
    code: 'AE',
  },
  AF: {
    countryName: 'Afghanistan',
    currency: 'AFN',
    symbol: 'Af',
    phcode: '93',
    code: 'AF',
  },
  AG: {
    countryName: 'Antigua and Barbuda',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1268',
    code: 'AG',
  },
  AI: {
    countryName: 'Anguilla',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1264',
    code: 'AI',
  },
  AL: {
    countryName: 'Albania',
    currency: 'ALL',
    symbol: 'ALL',
    dateFormat: 'yyyy-MM-dd',
    phcode: '355',
    code: 'AL',
  },
  AM: {
    countryName: 'Armenia',
    currency: 'AMD',
    symbol: 'AMD',
    phcode: '374',
    code: 'AM',
  },
  AO: {
    countryName: 'Angola',
    currency: 'AOA',
    symbol: 'AOA',
    phcode: '244',
    code: 'AO',
  },
  AR: {
    countryName: 'Argentina',
    currency: 'ARS',
    symbol: 'AR$',
    dateFormat: 'dd/MM/yyyy',
    phcode: '54',
    code: 'AR',
  },
  AS: {
    countryName: 'American Samoa',
    currency: 'USD',
    symbol: '$',
    phcode: '1684',
    code: 'AS',
  },
  AT: {
    countryName: 'Austria',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd.MM.yyyy',
    phcode: '43',
    code: 'AT',
  },
  AU: {
    countryName: 'Australia',
    currency: 'AUD',
    symbol: 'AU$',
    dateFormat: 'd/MM/yyyy',
    phcode: '61',
    code: 'AU',
  },
  AW: {
    countryName: 'Aruba',
    currency: 'AWG',
    symbol: 'AWG',
    phcode: '297',
    code: 'AW',
  },
  AX: {
    countryName: 'Aland Islands',
    currency: 'EUR',
    symbol: '€',
    phcode: '358',
    code: 'AX',
  },
  AZ: {
    countryName: 'Azerbaijan',
    currency: 'AZN',
    symbol: 'man.',
    phcode: '994',
    code: 'AZ',
  },
  BA: {
    countryName: 'Bosnia and Herzegovina',
    currency: 'BAM',
    symbol: 'KM',
    dateFormat: 'yyyy-MM-dd',
    phcode: '387',
    code: 'BA',
  },
  BB: {
    countryName: 'Barbados',
    currency: 'BBD',
    symbol: 'BBD',
    phcode: '1246',
    code: 'BB',
  },
  BD: {
    countryName: 'Bangladesh',
    currency: 'BDT',
    symbol: 'Tk',
    phcode: '880',
    code: 'BD',
  },
  BE: {
    countryName: 'Belgium',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd/MM/yyyy',
    phcode: '32',
    code: 'BE',
  },
  BF: {
    countryName: 'Burkina Faso',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '226',
    code: 'BF',
  },
  BG: {
    countryName: 'Bulgaria',
    currency: 'BGN',
    symbol: 'BGN',
    dateFormat: 'yyyy-M-d',
    phcode: '359',
    code: 'BG',
  },
  BH: {
    countryName: 'Bahrain',
    currency: 'BHD',
    symbol: 'BD',
    dateFormat: 'dd/MM/yyyy',
    phcode: '973',
    code: 'BH',
  },
  BI: {
    countryName: 'Burundi',
    currency: 'BIF',
    symbol: 'FBu',
    phcode: '257',
    code: 'BI',
  },
  BJ: {
    countryName: 'Benin',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '229',
    code: 'BJ',
  },
  BL: {
    countryName: 'Saint Barthelemy',
    currency: 'EUR',
    symbol: '€',
    phcode: '590',
    code: 'BL',
  },
  BM: {
    countryName: 'Bermuda',
    currency: 'BMD',
    symbol: 'BMD',
    phcode: '1441',
    code: 'BM',
  },
  BN: {
    countryName: 'Brunei',
    currency: 'BND',
    symbol: 'BN$',
    phcode: '673',
    code: 'BN',
  },
  BO: {
    countryName: 'Bolivia',
    currency: 'BOB',
    symbol: 'Bs',
    dateFormat: 'dd-MM-yyyy',
    phcode: '591',
    code: 'BO',
  },
  BQ: {
    countryName: 'Bonaire, Saint Eustatius and Saba ',
    currency: 'USD',
    symbol: '$',
    code: 'BQ',
  },
  BR: {
    countryName: 'Brazil',
    currency: 'BRL',
    symbol: 'R$',
    dateFormat: 'dd/MM/yyyy',
    phcode: '55',
    code: 'BR',
  },
  BS: {
    countryName: 'Bahamas',
    currency: 'BSD',
    symbol: 'BSD',
    phcode: '1242',
    code: 'BS',
  },
  BT: {
    countryName: 'Bhutan',
    currency: 'BTN',
    symbol: 'BTN',
    phcode: '975',
    code: 'BT',
  },
  BV: {
    countryName: 'Bouvet Island',
    currency: 'NOK',
    symbol: 'Nkr',
    phcode: '47',
    code: 'BV',
  },
  BW: {
    countryName: 'Botswana',
    currency: 'BWP',
    symbol: 'BWP',
    phcode: '267',
    code: 'BW',
  },
  BY: {
    countryName: 'Belarus',
    currency: 'BYN',
    symbol: 'BYN',
    dateFormat: 'd.M.yyyy',
    phcode: '375',
    code: 'BY',
  },
  BZ: {
    countryName: 'Belize',
    currency: 'BZD',
    symbol: 'BZ$',
    phcode: '501',
    code: 'BZ',
  },
  CA: {
    countryName: 'Canada',
    currency: 'CAD',
    symbol: 'CA$',
    dateFormat: 'dd/MM/yyyy',
    phcode: '1',
    code: 'CA',
  },
  CC: {
    countryName: 'Cocos Islands',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '61',
    code: 'CC',
  },
  CD: {
    countryName: 'Democratic Republic of the Congo',
    currency: 'CDF',
    symbol: 'CDF',
    phcode: '242',
    code: 'CD',
  },
  CF: {
    countryName: 'Central African Republic',
    currency: 'XAF',
    symbol: 'FCFA',
    phcode: '236',
    code: 'CF',
  },
  CG: {
    countryName: 'Republic of the Congo',
    currency: 'XAF',
    symbol: 'FCFA',
    phcode: '242',
    code: 'CG',
  },
  CH: {
    countryName: 'Switzerland',
    currency: 'CHF',
    symbol: 'CHF',
    dateFormat: 'dd.MM.yyyy',
    phcode: '41',
    code: 'CH',
  },
  CI: {
    countryName: 'Ivory Coast',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '225',
    code: 'CI',
  },
  CK: {
    countryName: 'Cook Islands',
    currency: 'NZD',
    symbol: 'NZ$',
    phcode: '682',
    code: 'CK',
  },
  CL: {
    countryName: 'Chile',
    currency: 'CLP',
    symbol: 'CL$',
    dateFormat: 'dd-MM-yyyy',
    phcode: '56',
    code: 'CL',
  },
  CM: {
    countryName: 'Cameroon',
    currency: 'XAF',
    symbol: 'FCFA',
    phcode: '237',
    code: 'CM',
  },
  CN: {
    countryName: 'China',
    currency: 'CNY',
    symbol: 'CN¥',
    dateFormat: 'yyyy-M-d',
    phcode: '86',
    code: 'CN',
  },
  CO: {
    countryName: 'Colombia',
    currency: 'COP',
    symbol: 'CO$',
    dateFormat: 'd/MM/yyyy',
    phcode: '57',
    code: 'CO',
  },
  CR: {
    countryName: 'Costa Rica',
    currency: 'CRC',
    symbol: '₡',
    dateFormat: 'dd/MM/yyyy',
    phcode: '506',
    code: 'CR',
  },
  CU: {
    countryName: 'Cuba',
    currency: 'CUP',
    symbol: 'CUP',
    phcode: '53',
    code: 'CU',
  },
  CV: {
    countryName: 'Cape Verde',
    currency: 'CVE',
    symbol: 'CV$',
    phcode: '238',
    code: 'CV',
  },
  CW: {countryName: 'Curacao', currency: 'ANG', symbol: 'ANG', code: 'CW'},
  CX: {
    countryName: 'Christmas Island',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '61',
    code: 'CX',
  },
  CY: {
    countryName: 'Cyprus',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd/MM/yyyy',
    phcode: '357',
    code: 'CY',
  },
  CZ: {
    countryName: 'Czech Republic',
    currency: 'CZK',
    symbol: 'Kč',
    dateFormat: 'd.M.yyyy',
    phcode: '420',
    code: 'CZ',
  },
  DE: {
    countryName: 'Germany',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd.MM.yyyy',
    phcode: '49',
    code: 'DE',
  },
  DJ: {
    countryName: 'Djibouti',
    currency: 'DJF',
    symbol: 'Fdj',
    phcode: '253',
    code: 'DJ',
  },
  DK: {
    countryName: 'Denmark',
    currency: 'DKK',
    symbol: 'Dkr',
    dateFormat: 'dd-MM-yyyy',
    phcode: '45',
    code: 'DK',
  },
  DM: {
    countryName: 'Dominica',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1767',
    code: 'DM',
  },
  DO: {
    countryName: 'Dominican Republic',
    currency: 'DOP',
    symbol: 'RD$',
    dateFormat: 'MM/dd/yyyy',
    phcode: '1809',
    code: 'DO',
  },
  DZ: {
    countryName: 'Algeria',
    currency: 'DZD',
    symbol: 'DA',
    dateFormat: 'dd/MM/yyyy',
    phcode: '213',
    code: 'DZ',
  },
  EC: {
    countryName: 'Ecuador',
    currency: 'USD',
    symbol: '$',
    dateFormat: 'dd/MM/yyyy',
    phcode: '593',
    code: 'EC',
  },
  EE: {
    countryName: 'Estonia',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd.MM.yyyy',
    phcode: '372',
    code: 'EE',
  },
  EG: {
    countryName: 'Egypt',
    currency: 'EGP',
    symbol: 'EGP',
    dateFormat: 'dd/MM/yyyy',
    phcode: '20',
    code: 'EG',
  },
  EH: {
    countryName: 'Western Sahara',
    currency: 'MAD',
    symbol: 'MAD',
    phcode: '212',
    code: 'EH',
  },
  ER: {
    countryName: 'Eritrea',
    currency: 'ERN',
    symbol: 'Nfk',
    phcode: '291',
    code: 'ER',
  },
  ES: {
    countryName: 'Spain',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd/MM/yyyy',
    phcode: '34',
    code: 'ES',
  },
  ET: {
    countryName: 'Ethiopia',
    currency: 'ETB',
    symbol: 'Br',
    phcode: '251',
    code: 'ET',
  },
  FI: {
    countryName: 'Finland',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd.M.yyyy',
    phcode: '358',
    code: 'FI',
  },
  FJ: {
    countryName: 'Fiji',
    currency: 'FJD',
    symbol: 'FJD',
    phcode: '679',
    code: 'FJ',
  },
  FK: {
    countryName: 'Falkland Islands',
    currency: 'FKP',
    symbol: 'FKP',
    phcode: '500',
    code: 'FK',
  },
  FM: {
    countryName: 'Micronesia',
    currency: 'USD',
    symbol: '$',
    phcode: '691',
    code: 'FM',
  },
  FO: {
    countryName: 'Faroe Islands',
    currency: 'DKK',
    symbol: 'Dkr',
    phcode: '298',
    code: 'FO',
  },
  FR: {
    countryName: 'France',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd/MM/yyyy',
    phcode: '33',
    code: 'FR',
  },
  GA: {
    countryName: 'Gabon',
    currency: 'XAF',
    symbol: 'FCFA',
    phcode: '241',
    code: 'GA',
  },
  GB: {
    countryName: 'United Kingdom',
    currency: 'GBP',
    symbol: '£',
    dateFormat: 'dd/MM/yyyy',
    phcode: '44',
    code: 'GB',
  },
  GD: {
    countryName: 'Grenada',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1473',
    code: 'GD',
  },
  GE: {
    countryName: 'Georgia',
    currency: 'GEL',
    symbol: 'GEL',
    phcode: '995',
    code: 'GE',
  },
  GF: {
    countryName: 'French Guiana',
    currency: 'EUR',
    symbol: '€',
    phcode: '594',
    code: 'GF',
  },
  GG: {
    countryName: 'Guernsey',
    currency: 'GBP',
    symbol: '£',
    phcode: '4414',
    code: 'GG',
  },
  GH: {
    countryName: 'Ghana',
    currency: 'GHS',
    symbol: 'GH₵',
    phcode: '233',
    code: 'GH',
  },
  GI: {
    countryName: 'Gibraltar',
    currency: 'GIP',
    symbol: 'GIP',
    phcode: '350',
    code: 'GI',
  },
  GL: {
    countryName: 'Greenland',
    currency: 'DKK',
    symbol: 'Dkr',
    phcode: '299',
    code: 'GL',
  },
  GM: {
    countryName: 'Gambia',
    currency: 'GMD',
    symbol: 'GMD',
    phcode: '220',
    code: 'GM',
  },
  GN: {
    countryName: 'Guinea',
    currency: 'GNF',
    symbol: 'FG',
    phcode: '224',
    code: 'GN',
  },
  GP: {
    countryName: 'Guadeloupe',
    currency: 'EUR',
    symbol: '€',
    phcode: '590',
    code: 'GP',
  },
  GQ: {
    countryName: 'Equatorial Guinea',
    currency: 'XAF',
    symbol: 'FCFA',
    phcode: '240',
    code: 'GQ',
  },
  GR: {
    countryName: 'Greece',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd/M/yyyy',
    phcode: '30',
    code: 'GR',
  },
  GS: {
    countryName: 'South Georgia and the South Sandwich Islands',
    currency: 'GBP',
    symbol: '£',
    phcode: '500',
    code: 'GS',
  },
  GT: {
    countryName: 'Guatemala',
    currency: 'GTQ',
    symbol: 'GTQ',
    dateFormat: 'd/MM/yyyy',
    phcode: '502',
    code: 'GT',
  },
  GU: {
    countryName: 'Guam',
    currency: 'USD',
    symbol: '$',
    phcode: '1671',
    code: 'GU',
  },
  GW: {
    countryName: 'Guinea-Bissau',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '245',
    code: 'GW',
  },
  GY: {
    countryName: 'Guyana',
    currency: 'GYD',
    symbol: 'GYD',
    phcode: '592',
    code: 'GY',
  },
  HK: {
    countryName: 'Hong Kong',
    currency: 'HKD',
    symbol: 'HK$',
    dateFormat: 'yyyy年M月d日',
    phcode: '852',
    code: 'HK',
  },
  HM: {
    countryName: 'Heard Island and McDonald Islands',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '672',
    code: 'HM',
  },
  HN: {
    countryName: 'Honduras',
    currency: 'HNL',
    symbol: 'HNL',
    dateFormat: 'MM-dd-yyyy',
    phcode: '504',
    code: 'HN',
  },
  HR: {
    countryName: 'Croatia',
    currency: 'HRK',
    symbol: 'kn',
    dateFormat: 'dd.MM.yyyy.',
    phcode: '385',
    code: 'HR',
  },
  HT: {
    countryName: 'Haiti',
    currency: 'HTG',
    symbol: 'HTG',
    phcode: '509',
    code: 'HT',
  },
  HU: {
    countryName: 'Hungary',
    currency: 'HUF',
    symbol: 'Ft',
    dateFormat: 'yyyy.MM.dd.',
    phcode: '36',
    code: 'HU',
  },
  ID: {
    countryName: 'Indonesia',
    currency: 'IDR',
    symbol: 'Rp',
    dateFormat: 'dd/MM/yyyy',
    phcode: '62',
    code: 'ID',
  },
  IE: {
    countryName: 'Ireland',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd/MM/yyyy',
    phcode: '353',
    code: 'IE',
  },
  IL: {
    countryName: 'Israel',
    currency: 'ILS',
    symbol: '₪',
    dateFormat: 'dd/MM/yyyy',
    phcode: '972',
    code: 'IL',
  },
  IM: {
    countryName: 'Isle of Man',
    currency: 'GBP',
    symbol: '£',
    phcode: '44',
    code: 'IM',
  },
  IN: {
    countryName: 'India',
    currency: 'INR',
    symbol: 'Rs',
    dateFormat: 'd/M/yyyy',
    phcode: '91',
    code: 'IN',
  },
  IO: {
    countryName: 'British Indian Ocean Territory',
    currency: 'USD',
    symbol: '$',
    phcode: '246',
    code: 'IO',
  },
  IQ: {
    countryName: 'Iraq',
    currency: 'IQD',
    symbol: 'IQD',
    dateFormat: 'dd/MM/yyyy',
    phcode: '964',
    code: 'IQ',
  },
  IR: {
    countryName: 'Iran',
    currency: 'IRR',
    symbol: 'IRR',
    phcode: '98',
    code: 'IR',
  },
  IS: {
    countryName: 'Iceland',
    currency: 'ISK',
    symbol: 'Ikr',
    dateFormat: 'd.M.yyyy',
    phcode: '354',
    code: 'IS',
  },
  IT: {
    countryName: 'Italy',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd/MM/yyyy',
    phcode: '39',
    code: 'IT',
  },
  JE: {
    countryName: 'Jersey',
    currency: 'GBP',
    symbol: '£',
    phcode: '4415',
    code: 'JE',
  },
  JM: {
    countryName: 'Jamaica',
    currency: 'JMD',
    symbol: 'J$',
    phcode: '1876',
    code: 'JM',
  },
  JO: {
    countryName: 'Jordan',
    currency: 'JOD',
    symbol: 'JD',
    dateFormat: 'dd/MM/yyyy',
    phcode: '962',
    code: 'JO',
  },
  JP: {
    countryName: 'Japan',
    currency: 'JPY',
    symbol: '¥',
    dateFormat: 'H24.MM.dd',
    phcode: '81',
    code: 'JP',
  },
  KE: {
    countryName: 'Kenya',
    currency: 'KES',
    symbol: 'Ksh',
    phcode: '254',
    code: 'KE',
  },
  KG: {
    countryName: 'Kyrgyzstan',
    currency: 'KGS',
    symbol: 'KGS',
    phcode: '996',
    code: 'KG',
  },
  KH: {
    countryName: 'Cambodia',
    currency: 'KHR',
    symbol: 'KHR',
    phcode: '855',
    code: 'KH',
  },
  KI: {
    countryName: 'Kiribati',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '686',
    code: 'KI',
  },
  KM: {
    countryName: 'Comoros',
    currency: 'KMF',
    symbol: 'CF',
    phcode: '269',
    code: 'KM',
  },
  KN: {
    countryName: 'Saint Kitts and Nevis',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1758',
    code: 'KN',
  },
  KP: {
    countryName: 'North Korea',
    currency: 'KPW',
    symbol: 'KPW',
    phcode: '850',
    code: 'KP',
  },
  KR: {
    countryName: 'South Korea',
    currency: 'KRW',
    symbol: '₩',
    dateFormat: 'yyyy. M. d',
    phcode: '82',
    code: 'KR',
  },
  KW: {
    countryName: 'Kuwait',
    currency: 'KWD',
    symbol: 'KD',
    dateFormat: 'dd/MM/yyyy',
    phcode: '965',
    code: 'KW',
  },
  KY: {
    countryName: 'Cayman Islands',
    currency: 'KYD',
    symbol: 'KYD',
    phcode: '1345',
    code: 'KY',
  },
  KZ: {
    countryName: 'Kazakhstan',
    currency: 'KZT',
    symbol: 'KZT',
    phcode: '7',
    code: 'KZ',
  },
  LA: {
    countryName: 'Laos',
    currency: 'LAK',
    symbol: 'LAK',
    phcode: '856',
    code: 'LA',
  },
  LB: {
    countryName: 'Lebanon',
    currency: 'LBP',
    symbol: 'LB£',
    dateFormat: 'dd/MM/yyyy',
    phcode: '961',
    code: 'LB',
  },
  LC: {
    countryName: 'Saint Lucia',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1758',
    code: 'LC',
  },
  LI: {
    countryName: 'Liechtenstein',
    currency: 'CHF',
    symbol: 'CHF',
    phcode: '423',
    code: 'LI',
  },
  LK: {
    countryName: 'Sri Lanka',
    currency: 'LKR',
    symbol: 'SLRs',
    phcode: '94',
    code: 'LK',
  },
  LR: {
    countryName: 'Liberia',
    currency: 'LRD',
    symbol: 'LRD',
    phcode: '231',
    code: 'LR',
  },
  LS: {
    countryName: 'Lesotho',
    currency: 'LSL',
    symbol: 'LSL',
    phcode: '266',
    code: 'LS',
  },
  LT: {
    countryName: 'Lithuania',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'yyyy.M.d',
    phcode: '370',
    code: 'LT',
  },
  LU: {
    countryName: 'Luxembourg',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd.MM.yyyy',
    phcode: '352',
    code: 'LU',
  },
  LV: {
    countryName: 'Latvia',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'yyyy.d.M',
    phcode: '371',
    code: 'LV',
  },
  LY: {
    countryName: 'Libya',
    currency: 'LYD',
    symbol: 'LD',
    dateFormat: 'dd/MM/yyyy',
    phcode: '218',
    code: 'LY',
  },
  MA: {
    countryName: 'Morocco',
    currency: 'MAD',
    symbol: 'MAD',
    dateFormat: 'dd/MM/yyyy',
    phcode: '212',
    code: 'MA',
  },
  MC: {
    countryName: 'Monaco',
    currency: 'EUR',
    symbol: '€',
    phcode: '377',
    code: 'MC',
  },
  MD: {
    countryName: 'Moldova',
    currency: 'MDL',
    symbol: 'MDL',
    phcode: '373',
    code: 'MD',
  },
  ME: {
    countryName: 'Montenegro',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd.M.yyyy.',
    phcode: '382',
    code: 'ME',
  },
  MF: {
    countryName: 'Saint Martin',
    currency: 'EUR',
    symbol: '€',
    phcode: '590',
    code: 'MF',
  },
  MG: {
    countryName: 'Madagascar',
    currency: 'MGA',
    symbol: 'MGA',
    phcode: '261',
    code: 'MG',
  },
  MH: {
    countryName: 'Marshall Islands',
    currency: 'USD',
    symbol: '$',
    phcode: '692',
    code: 'MH',
  },
  MK: {
    countryName: 'Macedonia',
    currency: 'MKD',
    symbol: 'MKD',
    dateFormat: 'd.M.yyyy',
    phcode: '389',
    code: 'MK',
  },
  ML: {
    countryName: 'Mali',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '223',
    code: 'ML',
  },
  MM: {
    countryName: 'Myanmar',
    currency: 'MMK',
    symbol: 'MMK',
    phcode: '95',
    code: 'MM',
  },
  MN: {
    countryName: 'Mongolia',
    currency: 'MNT',
    symbol: 'MNT',
    phcode: '976',
    code: 'MN',
  },
  MO: {
    countryName: 'Macao',
    currency: 'MOP',
    symbol: 'MOP$',
    phcode: '853',
    code: 'MO',
  },
  MP: {
    countryName: 'Northern Mariana Islands',
    currency: 'USD',
    symbol: '$',
    phcode: '1670',
    code: 'MP',
  },
  MQ: {
    countryName: 'Martinique',
    currency: 'EUR',
    symbol: '€',
    phcode: '596',
    code: 'MQ',
  },
  MR: {
    countryName: 'Mauritania',
    currency: 'MRU',
    symbol: 'MRU',
    phcode: '222',
    code: 'MR',
  },
  MS: {
    countryName: 'Montserrat',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1664',
    code: 'MS',
  },
  MT: {
    countryName: 'Malta',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd/MM/yyyy',
    phcode: '356',
    code: 'MT',
  },
  MU: {
    countryName: 'Mauritius',
    currency: 'MUR',
    symbol: 'MURs',
    phcode: '230',
    code: 'MU',
  },
  MV: {
    countryName: 'Maldives',
    currency: 'MVR',
    symbol: 'MVR',
    phcode: '960',
    code: 'MV',
  },
  MW: {
    countryName: 'Malawi',
    currency: 'MWK',
    symbol: 'MWK',
    phcode: '265',
    code: 'MW',
  },
  MX: {
    countryName: 'Mexico',
    currency: 'MXN',
    symbol: 'MX$',
    dateFormat: 'd/MM/yyyy',
    phcode: '52',
    code: 'MX',
  },
  MY: {
    countryName: 'Malaysia',
    currency: 'MYR',
    symbol: 'RM',
    dateFormat: 'dd/MM/yyyy',
    phcode: '60',
    code: 'MY',
  },
  MZ: {
    countryName: 'Mozambique',
    currency: 'MZN',
    symbol: 'MTn',
    phcode: '258',
    code: 'MZ',
  },
  NA: {
    countryName: 'Namibia',
    currency: 'NAD',
    symbol: 'N$',
    phcode: '264',
    code: 'NA',
  },
  NC: {
    countryName: 'New Caledonia',
    currency: 'XPF',
    symbol: 'XPF',
    phcode: '687',
    code: 'NC',
  },
  NE: {
    countryName: 'Niger',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '227',
    code: 'NE',
  },
  NF: {
    countryName: 'Norfolk Island',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '672',
    code: 'NF',
  },
  NG: {
    countryName: 'Nigeria',
    currency: 'NGN',
    symbol: '₦',
    phcode: '234',
    code: 'NG',
  },
  NI: {
    countryName: 'Nicaragua',
    currency: 'NIO',
    symbol: 'C$',
    dateFormat: 'MM-dd-yyyy',
    phcode: '505',
    code: 'NI',
  },
  NL: {
    countryName: 'Netherlands',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd-M-yyyy',
    phcode: '31',
    code: 'NL',
  },
  NO: {
    countryName: 'Norway',
    currency: 'NOK',
    symbol: 'Nkr',
    dateFormat: 'dd.MM.yyyy',
    phcode: '47',
    code: 'NO',
  },
  NP: {
    countryName: 'Nepal',
    currency: 'NPR',
    symbol: 'NPRs',
    phcode: '977',
    code: 'NP',
  },
  NR: {
    countryName: 'Nauru',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '674',
    code: 'NR',
  },
  NU: {
    countryName: 'Niue',
    currency: 'NZD',
    symbol: 'NZ$',
    phcode: '683',
    code: 'NU',
  },
  NZ: {
    countryName: 'New Zealand',
    currency: 'NZD',
    symbol: 'NZ$',
    dateFormat: 'd/MM/yyyy',
    phcode: '64',
    code: 'NZ',
  },
  OM: {
    countryName: 'Oman',
    currency: 'OMR',
    symbol: 'OMR',
    dateFormat: 'dd/MM/yyyy',
    phcode: '968',
    code: 'OM',
  },
  PA: {
    countryName: 'Panama',
    currency: 'PAB',
    symbol: 'B/.',
    dateFormat: 'MM/dd/yyyy',
    phcode: '507',
    code: 'PA',
  },
  PE: {
    countryName: 'Peru',
    currency: 'PEN',
    symbol: 'S/.',
    dateFormat: 'dd/MM/yyyy',
    phcode: '51',
    code: 'PE',
  },
  PF: {
    countryName: 'French Polynesia',
    currency: 'XPF',
    symbol: 'XPF',
    phcode: '689',
    code: 'PF',
  },
  PG: {
    countryName: 'Papua New Guinea',
    currency: 'PGK',
    symbol: 'PGK',
    phcode: '675',
    code: 'PG',
  },
  PH: {
    countryName: 'Philippines',
    currency: 'PHP',
    symbol: '₱',
    dateFormat: 'M/d/yyyy',
    phcode: '63',
    code: 'PH',
  },
  PK: {
    countryName: 'Pakistan',
    currency: 'PKR',
    symbol: 'PKRs',
    phcode: '92',
    code: 'PK',
  },
  PL: {
    countryName: 'Poland',
    currency: 'PLN',
    symbol: 'zł',
    dateFormat: 'dd.MM.yyyy',
    phcode: '48',
    code: 'PL',
  },
  PM: {
    countryName: 'Saint Pierre and Miquelon',
    currency: 'EUR',
    symbol: '€',
    phcode: '508',
    code: 'PM',
  },
  PN: {
    countryName: 'Pitcairn',
    currency: 'NZD',
    symbol: 'NZ$',
    phcode: '64',
    code: 'PN',
  },
  PR: {
    countryName: 'Puerto Rico',
    currency: 'USD',
    symbol: '$',
    dateFormat: 'MM-dd-yyyy',
    phcode: '1787',
    code: 'PR',
  },
  PS: {
    countryName: 'Palestinian Territory',
    currency: 'ILS',
    symbol: '₪',
    phcode: '970',
    code: 'PS',
  },
  PT: {
    countryName: 'Portugal',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'dd-MM-yyyy',
    phcode: '351',
    code: 'PT',
  },
  PW: {
    countryName: 'Palau',
    currency: 'USD',
    symbol: '$',
    phcode: '680',
    code: 'PW',
  },
  PY: {
    countryName: 'Paraguay',
    currency: 'PYG',
    symbol: '₲',
    dateFormat: 'dd/MM/yyyy',
    phcode: '595',
    code: 'PY',
  },
  QA: {
    countryName: 'Qatar',
    currency: 'QAR',
    symbol: 'QR',
    dateFormat: 'dd/MM/yyyy',
    phcode: '974',
    code: 'QA',
  },
  RE: {
    countryName: 'Reunion',
    currency: 'EUR',
    symbol: '€',
    phcode: '262',
    code: 'RE',
  },
  RO: {
    countryName: 'Romania',
    currency: 'RON',
    symbol: 'RON',
    dateFormat: 'dd.MM.yyyy',
    phcode: '40',
    code: 'RO',
  },
  RS: {
    countryName: 'Serbia',
    currency: 'RSD',
    symbol: 'din.',
    dateFormat: 'd.M.yyyy.',
    phcode: '381',
    code: 'RS',
  },
  RU: {
    countryName: 'Russia',
    currency: 'RUB',
    symbol: 'RUB',
    dateFormat: 'dd.MM.yyyy',
    phcode: '7',
    code: 'RU',
  },
  RW: {
    countryName: 'Rwanda',
    currency: 'RWF',
    symbol: 'RWF',
    phcode: '250',
    code: 'RW',
  },
  SA: {
    countryName: 'Saudi Arabia',
    currency: 'SAR',
    symbol: 'SR',
    dateFormat: 'dd/MM/yyyy',
    phcode: '966',
    code: 'SA',
  },
  SB: {
    countryName: 'Solomon Islands',
    currency: 'SBD',
    symbol: 'SBD',
    phcode: '677',
    code: 'SB',
  },
  SC: {
    countryName: 'Seychelles',
    currency: 'SCR',
    symbol: 'SCR',
    phcode: '248',
    code: 'SC',
  },
  SD: {
    countryName: 'Sudan',
    currency: 'SDG',
    symbol: 'SDG',
    dateFormat: 'dd/MM/yyyy',
    phcode: '249',
    code: 'SD',
  },
  SE: {
    countryName: 'Sweden',
    currency: 'SEK',
    symbol: 'Skr',
    dateFormat: 'yyyy-MM-dd',
    phcode: '46',
    code: 'SE',
  },
  SG: {
    countryName: 'Singapore',
    currency: 'SGD',
    symbol: 'S$',
    dateFormat: 'M/d/yyyy',
    phcode: '65',
    code: 'SG',
  },
  SH: {
    countryName: 'Saint Helena',
    currency: 'SHP',
    symbol: 'SHP',
    phcode: '290',
    code: 'SH',
  },
  SI: {
    countryName: 'Slovenia',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd.M.yyyy',
    phcode: '386',
    code: 'SI',
  },
  SJ: {
    countryName: 'Svalbard and Jan Mayen',
    currency: 'NOK',
    symbol: 'Nkr',
    phcode: '47',
    code: 'SJ',
  },
  SK: {
    countryName: 'Slovakia',
    currency: 'EUR',
    symbol: '€',
    dateFormat: 'd.M.yyyy',
    phcode: '421',
    code: 'SK',
  },
  SL: {
    countryName: 'Sierra Leone',
    currency: 'SLL',
    symbol: 'SLL',
    phcode: '232',
    code: 'SL',
  },
  SM: {
    countryName: 'San Marino',
    currency: 'EUR',
    symbol: '€',
    phcode: '378',
    code: 'SM',
  },
  SN: {
    countryName: 'Senegal',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '221',
    code: 'SN',
  },
  SO: {
    countryName: 'Somalia',
    currency: 'SOS',
    symbol: 'Ssh',
    phcode: '252',
    code: 'SO',
  },
  SR: {
    countryName: 'Suriname',
    currency: 'SRD',
    symbol: 'SRD',
    phcode: '597',
    code: 'SR',
  },
  SS: {
    countryName: 'South Sudan',
    currency: 'SSP',
    symbol: 'SSP',
    phcode: '211',
    code: 'SS',
  },
  ST: {
    countryName: 'Sao Tome and Principe',
    currency: 'STD',
    symbol: 'STD',
    phcode: '239',
    code: 'ST',
  },
  SV: {
    countryName: 'El Salvador',
    currency: 'USD',
    symbol: '$',
    dateFormat: 'MM-dd-yyyy',
    phcode: '503',
    code: 'SV',
  },
  SX: {countryName: 'Sint Maarten', currency: 'ANG', symbol: 'ANG', code: 'SX'},
  SY: {
    countryName: 'Syria',
    currency: 'SYP',
    symbol: 'SY£',
    dateFormat: 'dd/MM/yyyy',
    phcode: '963',
    code: 'SY',
  },
  SZ: {
    countryName: 'Swaziland',
    currency: 'SZL',
    symbol: 'SZL',
    phcode: '268',
    code: 'SZ',
  },
  TC: {
    countryName: 'Turks and Caicos Islands',
    currency: 'USD',
    symbol: '$',
    phcode: '1649',
    code: 'TC',
  },
  TD: {
    countryName: 'Chad',
    currency: 'XAF',
    symbol: 'FCFA',
    phcode: '235',
    code: 'TD',
  },
  TF: {
    countryName: 'French Southern Territories',
    currency: 'EUR',
    symbol: '€',
    phcode: '689',
    code: 'TF',
  },
  TG: {
    countryName: 'Togo',
    currency: 'XOF',
    symbol: 'CFA',
    phcode: '228',
    code: 'TG',
  },
  TH: {
    countryName: 'Thailand',
    currency: 'THB',
    symbol: '฿',
    dateFormat: '๓/๖/๒๕๕๕',
    phcode: '66',
    code: 'TH',
  },
  TJ: {
    countryName: 'Tajikistan',
    currency: 'TJS',
    symbol: 'TJS',
    phcode: '992',
    code: 'TJ',
  },
  TK: {
    countryName: 'Tokelau',
    currency: 'NZD',
    symbol: 'NZ$',
    phcode: '690',
    code: 'TK',
  },
  TL: {
    countryName: 'East Timor',
    currency: 'USD',
    symbol: '$',
    phcode: '670',
    code: 'TL',
  },
  TM: {
    countryName: 'Turkmenistan',
    currency: 'TMT',
    symbol: 'TMT',
    phcode: '993',
    code: 'TM',
  },
  TN: {
    countryName: 'Tunisia',
    currency: 'TND',
    symbol: 'DT',
    dateFormat: 'dd/MM/yyyy',
    phcode: '216',
    code: 'TN',
  },
  TO: {
    countryName: 'Tonga',
    currency: 'TOP',
    symbol: 'T$',
    phcode: '676',
    code: 'TO',
  },
  TR: {
    countryName: 'Turkey',
    currency: 'TRY',
    symbol: 'TL',
    dateFormat: 'dd.MM.yyyy',
    phcode: '90',
    code: 'TR',
  },
  TT: {
    countryName: 'Trinidad and Tobago',
    currency: 'TTD',
    symbol: 'TT$',
    phcode: '1868',
    code: 'TT',
  },
  TV: {
    countryName: 'Tuvalu',
    currency: 'AUD',
    symbol: 'AU$',
    phcode: '688',
    code: 'TV',
  },
  TW: {
    countryName: 'Taiwan',
    currency: 'TWD',
    symbol: 'NT$',
    dateFormat: 'yyyy/M/d',
    phcode: '886',
    code: 'TW',
  },
  TZ: {
    countryName: 'Tanzania',
    currency: 'TZS',
    symbol: 'TSh',
    phcode: '255',
    code: 'TZ',
  },
  UA: {
    countryName: 'Ukraine',
    currency: 'UAH',
    symbol: '₴',
    dateFormat: 'dd.MM.yyyy',
    phcode: '380',
    code: 'UA',
  },
  UG: {
    countryName: 'Uganda',
    currency: 'UGX',
    symbol: 'USh',
    phcode: '256',
    code: 'UG',
  },
  UM: {
    countryName: 'United States Minor Outlying Islands',
    currency: 'USD',
    symbol: '$',
    phcode: '699',
    code: 'UM',
  },
  US: {
    countryName: 'United States',
    currency: 'USD',
    symbol: '$',
    dateFormat: 'M/d/yyyy',
    phcode: '1',
    code: 'US',
  },
  UY: {
    countryName: 'Uruguay',
    currency: 'UYU',
    symbol: '$U',
    dateFormat: 'dd/MM/yyyy',
    phcode: '598',
    code: 'UY',
  },
  UZ: {
    countryName: 'Uzbekistan',
    currency: 'UZS',
    symbol: 'UZS',
    phcode: '998',
    code: 'UZ',
  },
  VA: {
    countryName: 'Vatican',
    currency: 'EUR',
    symbol: '€',
    phcode: '379',
    code: 'VA',
  },
  VC: {
    countryName: 'Saint Vincent and the Grenadines',
    currency: 'XCD',
    symbol: 'XCD',
    phcode: '1784',
    code: 'VC',
  },
  VE: {
    countryName: 'Venezuela',
    currency: 'VEF',
    symbol: 'Bs.F.',
    dateFormat: 'dd/MM/yyyy',
    phcode: '58',
    code: 'VE',
  },
  VG: {
    countryName: 'British Virgin Islands',
    currency: 'USD',
    symbol: '$',
    phcode: '1284',
    code: 'VG',
  },
  VI: {
    countryName: 'U.S. Virgin Islands',
    currency: 'USD',
    symbol: '$',
    phcode: '1340',
    code: 'VI',
  },
  VN: {
    countryName: 'Vietnam',
    currency: 'VND',
    symbol: '₫',
    dateFormat: 'dd/MM/yyyy',
    phcode: '84',
    code: 'VN',
  },
  VU: {
    countryName: 'Vanuatu',
    currency: 'VUV',
    symbol: 'VUV',
    phcode: '678',
    code: 'VU',
  },
  WF: {
    countryName: 'Wallis and Futuna',
    currency: 'XPF',
    symbol: 'XPF',
    phcode: '681',
    code: 'WF',
  },
  WS: {
    countryName: 'Samoa',
    currency: 'WST',
    symbol: 'WST',
    phcode: '685',
    code: 'WS',
  },
  XK: {countryName: 'Kosovo', currency: 'EUR', symbol: '€', code: 'XK'},
  YE: {
    countryName: 'Yemen',
    currency: 'YER',
    symbol: 'YR',
    dateFormat: 'dd/MM/yyyy',
    phcode: '967',
    code: 'YE',
  },
  YT: {
    countryName: 'Mayotte',
    currency: 'EUR',
    symbol: '€',
    phcode: '262',
    code: 'YT',
  },
  ZA: {
    countryName: 'South Africa',
    currency: 'ZAR',
    symbol: 'R',
    dateFormat: 'yyyy/MM/dd',
    phcode: '27',
    code: 'ZA',
  },
  ZM: {
    countryName: 'Zambia',
    currency: 'ZMW',
    symbol: 'ZK',
    phcode: '260',
    code: 'ZM',
  },
  ZW: {
    countryName: 'Zimbabwe',
    currency: 'ZWL',
    symbol: 'ZWL',
    phcode: '263',
    code: 'ZW',
  },
};
